/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as TimestampImport } from './routes/timestamp';
import { Route as EpubImport } from './routes/epub';
import { Route as Base64Import } from './routes/base64';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const TimestampRoute = TimestampImport.update({
  id: '/timestamp',
  path: '/timestamp',
  getParentRoute: () => rootRoute,
} as any);

const EpubRoute = EpubImport.update({
  id: '/epub',
  path: '/epub',
  getParentRoute: () => rootRoute,
} as any);

const Base64Route = Base64Import.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/base64': {
      id: '/base64';
      path: '/base64';
      fullPath: '/base64';
      preLoaderRoute: typeof Base64Import;
      parentRoute: typeof rootRoute;
    };
    '/epub': {
      id: '/epub';
      path: '/epub';
      fullPath: '/epub';
      preLoaderRoute: typeof EpubImport;
      parentRoute: typeof rootRoute;
    };
    '/timestamp': {
      id: '/timestamp';
      path: '/timestamp';
      fullPath: '/timestamp';
      preLoaderRoute: typeof TimestampImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/base64': typeof Base64Route;
  '/epub': typeof EpubRoute;
  '/timestamp': typeof TimestampRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/base64': typeof Base64Route;
  '/epub': typeof EpubRoute;
  '/timestamp': typeof TimestampRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/base64': typeof Base64Route;
  '/epub': typeof EpubRoute;
  '/timestamp': typeof TimestampRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/base64' | '/epub' | '/timestamp';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/base64' | '/epub' | '/timestamp';
  id: '__root__' | '/' | '/base64' | '/epub' | '/timestamp';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  Base64Route: typeof Base64Route;
  EpubRoute: typeof EpubRoute;
  TimestampRoute: typeof TimestampRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Base64Route: Base64Route,
  EpubRoute: EpubRoute,
  TimestampRoute: TimestampRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/base64",
        "/epub",
        "/timestamp"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/base64": {
      "filePath": "base64.tsx"
    },
    "/epub": {
      "filePath": "epub.tsx"
    },
    "/timestamp": {
      "filePath": "timestamp.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
