on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    secrets: inherit
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
