name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Convert to pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: dist/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
