name: Run Tests
on:
  push:

jobs:
  test:
    name: Run Unit Tests
    uses: ./.github/workflows/_unit_test.yml
    secrets: inherit

  lint:
    name: Lint Code
    uses: ./.github/workflows/_lint.yml
    secrets: inherit
